---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quote-frontend-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wtistang/quote-frontend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quote-frontend-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/kabanero/quote-frontend:tkn

